HTTPSConnectionPool(host='sec-ucentral-qa01.cicd.lab.wlan.tip.build', port=16001): Max retries exceeded with url: /api/v1/oauth2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f00561c8250>: Failed to establish a new connection: [Errno -2] Name or service not known'))